const UserActionTypes = {
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR: 'SIGNOUT_ERROR'
};

export default UserActionTypes;